name: GitHub Actions Demo
run-name: GitHub Actions Demo

on:
  workflow_dispatch:

jobs:
  Container_Image_Build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set TIMESTAMP
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M)
          echo ${{ env.TIMESTAMP }}
