name: GitHub Actions Demo3
run-name: GitHub Actions Demo is testing out GitHub Actions

on:
  workflow_dispatch:

jobs:
  Container_Image_Build:
    runs-on: [self-hosted, X64, ubuntu-latest, general]
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set TIMESTAMP
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M)
          echo ${{ env.TIMESTAMP }}
