name: GitHub Actions Demo
run-name: GitHub Actions Demo

on:
  workflow_dispatch:
    inputs:
      flag:
        type: boolean
        required: true
        description: "deploy_flag"
      IMAGE_TAG:
        type: choice
        required: true
        options:
          - ""
          - "dir1"
          - "dir2"
          - "dir3"

jobs:
  Container_Image_Build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Image Tag
        run: |
          echo "option: ${{ github.event.inputs.choice }}"
